name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vigmurug/ci-cd-setup-test:latest

      - name: Verify Pushed Image
        run: docker pull vigmurug/ci-cd-setup-test:latest